#!/usr/bin/env bash
set -euo pipefail

export SUMMER_SCHOOL_RUN_PRUNE=true
export SUMMER_SCHOOL_RUN_MAPPER=false
export SUMMER_SCHOOL_RUN_RVIZ=true
# Replay is driven from a separate terminal so rosbag play can be paused.
export SUMMER_SCHOOL_RUN_REPLAY_RAW=false
export SUMMER_SCHOOL_RUN_REPLAY_PRUNE=false
export SUMMER_SCHOOL_RUN_REPLAY_SKY_MASK=false
export SUMMER_SCHOOL_RUN_REPLAY_LOCALIZATION=false
export SUMMER_SCHOOL_RUN_RQT_RECONFIGURE=true
export SUMMER_SCHOOL_REPLAY_MODE=prune
export SUMMER_SCHOOL_PRUNE_DEBUG_PROJECT_LIDAR=true
export SUMMER_SCHOOL_PRUNE_DEBUG_PROJECT_LIDAR_STRIDE=1
export SUMMER_SCHOOL_PRUNE_DEBUG_PROJECT_LIDAR_RADIUS=2
export SUMMER_SCHOOL_PRUNE_DEBUG_PROJECT_LIDAR_OUTLINE_ONLY=false
export SUMMER_SCHOOL_PRUNE_OVERLAY_OUTPUT_DIR=/workspace/demo/logs/overlays
export SUMMER_SCHOOL_PRUNE_OVERLAY_OUTPUT_STRIDE=1
export SUMMER_SCHOOL_PRUNE_OVERLAY_DOT_RADIUS=2

exec "$(dirname "$0")/run_demo.sh" "$@"
